In [2]:
import torch
x=torch.tensor([[1,2],[3,2]], dtype=torch.float32)

In [3]:
print(x.shape)
print(x.ndim)
print(x.dtype)
print(x.device)

torch.Size([2, 2])
2
torch.float32
cpu


# Creating tensors

In [5]:
# Zeros
a=torch.zeros((2,3))
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
# Ones 
b=torch.ones(((2,3)))
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
# random numbers between 0 to 1

a= torch.rand((2,3))         #uniform [0,1]
a

tensor([[0.9676, 0.2646, 0.2268],
        [0.8074, 0.1334, 0.0842]])

In [12]:
# random numbers (normal distribution)
b=torch.randn((2,3))
b

tensor([[-0.7666,  0.5488, -0.1342],
        [-1.2257, -0.3139, -0.1171]])

In [15]:
# a x b matrix of a specific number
a=torch.full((2,3),7)
a

tensor([[7, 7, 7],
        [7, 7, 7]])

In [17]:
# identity matrix
a= torch.eye(3)
a


tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [23]:
# integers from x to y-1
a=torch.arange(0,6)
a

tensor([0, 1, 2, 3, 4, 5])

In [26]:
# All of the above can be implemented by numpy

# Indexing and Slicing

In [27]:
x= torch.tensor([[1,2,3],[4,5,6]])
# First row
x[0]

tensor([1, 2, 3])

In [28]:
# second column
x[:,1]

tensor([2, 5])

In [29]:
# Element pick 
x[1,2]

tensor(6)

In [33]:
# Last rows
x[-1]

# last column = x[:,-1]

tensor([4, 5, 6])

In [ ]:
# Slice rows 
x[